### ISSUE TITLE
Is Readme incomplete for data?

### ISSUE THREAD

**Issue by amitamb** [dgraph-io/benchmarks#14]
I am referring to readme here

https://github.com/dgraph-io/benchmarks/blob/master/data/README.md

It refers to different files but following files are not checked in

names.gz
rdf-films.gz

names.gz is surely not there. But rdf-films.gz is there but renamed somehow?

Can someone please clear this?

**Comment by danielmai** [comment]
Hi @amitamb. The README.md has not been updated in a while. The names.gz and rdf-films.gz data sets were merged into what's now the 21million.rdf.gz and 21million.schema files (see 69179aa32aa64d0db138c5fc6475cb43bc08f25c and then 226773af52cb0b3ac15e89ef3f9be8513e6c1982).

It's currently not a priority update the README, though you could walk through the commit history like I did above and see how the files changed over time. And of course, you can always [examine](url) and verify the data sets in this repo.
