### ISSUE TITLE
Is there an error in release.schema?

### ISSUE THREAD

**Issue by Valdanitooooo** [dgraph-io/benchmarks#36]
data/release/release.schema file.
```
type Actor {
    name: string
    actor.film: [Film]
    actor.dubbing_performances: [Film]
}
```
Is it correct to change to `actor.film: [Performance]`？

**Comment by MichelDiz** [comment]
Hey, in the current and upcoming version the definition will be simpler see => https://docs.dgraph.io/query-language/#type-system. For example, this type would look like this:
```
type Actor {
    name
    actor.film
    actor.dubbing_performances
}
```

Cheers.
