### ISSUE TITLE
Add test code to Arangos big comparison  

### ISSUE THREAD

**Issue by ShalokShalom** [dgraph-io/benchmarks#8]
ArangoDB added an imho interesting comparison to its homepage and the comment section is full with requests for dgraph:

https://www.arangodb.com/2018/02/nosql-performance-benchmark-2018-mongodb-postgresql-orientdb-neo4j-arangodb/

Based on the results with neo4j on your own blog and this results is it obvious that dgraph might probably provide super results.

This a chance to make dgraph even more popular :D

**Comment by ShalokShalom** [comment]
Note: neo4j's recently added chances increase their performance and their memory usage. 

Dgraph will probably still perform remarkable speedier as dgraph and probably also as other databases here. :)

**Comment by manishrjain** [comment]
We'd love to add, but we're pretty swamped at the moment. So, this integration would have to come from the community.
